# This deployment will run as root, using Tanzu Mission Control's
# policy for privileged containers.
# The create_sa.sh script will create a service account, and we
# then use that SA here (abagdemo-priv).
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abagdemo 
  namespace: abagdemo
  labels:
    app: abagdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abagdemo 
  template:
    metadata:
      labels:
        app: abagdemo
    spec:
      serviceAccountName: abagdemo-priv
      containers:
      - name: abagdemo
        image: fckuligowski/abagdemo:v1.3.4
        ports:
        - containerPort: 5000
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/home/abagdemo/instance/creds/hazel-math-279814.json"
        command: ["/bin/sh", "/abagdemo/runit.sh"]
        volumeMounts:
        - name: gcp-creds
          mountPath: "/home/abagdemo/instance/creds"
      volumes:
        - name: gcp-creds
          secret:
            secretName: abagdemo-gcp-creds
