apiVersion: v1
data:
  default.conf: |-
    server {
        listen       8080;
        listen       8443 ssl;
        ssl_certificate      /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key  /etc/nginx/ssl/nginx.key;
        ssl_protocols TLSv1.2;
        ssl_ciphers EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:!EECDH+3DES:!RSA+3DES:!MD5;
        ssl_prefer_server_ciphers on;        
        server_name  localhost;
        location / {
            proxy_pass  http://localhost:5000/;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
kind: ConfigMap
metadata:
  name: abagdemo-nginx-config
  namespace: abagdemo