# The first server{} section redirects all http traffic (port 8080) to https
# The second server{} section contains the setup for https SSL and its certs
# This tells nginx to listen on port 8080 (http) and 8443 (https) because 
# ports 80 and 443 are restricted/privileged ports and nginx won't boot up
# in a pod container with those port numbers. 
# In the service definition, we tell it to listen on port 80 and 443, and to
# send those to targetPort 8080 and 8443.
# With that, nginx can run as a non-privileged container, yet listen on the
# normal ports for http/s traffic.
apiVersion: v1
data:
  default.conf: |-
    server {
        listen 8080 default_server;
        server_name _;
        return 301 https://$host$request_uri;
    }

    server {
        listen       8443 ssl;
        ssl_certificate      /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key  /etc/nginx/ssl/nginx.key;
        ssl_protocols TLSv1.2;
        ssl_ciphers EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:!EECDH+3DES:!RSA+3DES:!MD5;
        ssl_prefer_server_ciphers on;        
        server_name  localhost;
        location / {
            proxy_pass  http://localhost:5000/;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
kind: ConfigMap
metadata:
  name: abagdemo-nginx-config
  namespace: abagdemo