apiVersion: pksapi.io/v1beta1
kind: LogSink
metadata:
   name: log-sink
   namespace: abagdemo
spec:
   type: syslog
   host: syslog.tkg-eu.kuligof.com
   port: 5014
   enable_tls: true
---
apiVersion: pksapi.io/v1beta1
kind: ClusterLogSink
metadata:
   name: cluster-log-sink
spec:
   type: syslog
   host: syslog.tkg-eu.kuligof.com
   port: 5014
   enable_tls: true