apiVersion: pksapi.io/v1beta1
kind: LogSink
metadata:
   name: log-sink
   namespace: abagdemo
spec:
   type: syslog
   host: ec2-34-247-39-118.eu-west-1.compute.amazonaws.com
   port: 5014
   enable_tls: true
---
apiVersion: pksapi.io/v1beta1
kind: ClusterLogSink
metadata:
   name: cluster-log-sink
spec:
   type: syslog
   host: ec2-34-247-39-118.eu-west-1.compute.amazonaws.com
   port: 5014
   enable_tls: true